const logoMeta = {
  alan: { displayName: "Alan AI" },
  aws: { displayName: "AWS" },
  cpp: { displayName: "C++" },
  csharp: { displayName: "C#" },
  css: { displayName: "CSS" },
  louisvuitton: { displayName: "Louis Vuitton" },
  jnj: { displayName: "Johnson & Johnson" },
  ts: { displayName: "TypeScript" },
  js: { displayName: "JavaScript" },
  php: { displayName: "php" },
  kfc: { displayName: "KFC" },
  reactnative: { displayName: "React Native" },
  buymeacoffee: { displayName: "Buy Me a Coffee" },
  bmw: { displayName: "BMW" },
  burgerking: { displayName: "BurgerKing" },
  hsbc: { displayName: "HSBC" },
  phonepe: { displayName: "PhonePe" },
  rayban: { displayName: "Ray-Ban" },
  mysql: { displayName: "MySQL" },
  opensea: { displayName: "OpenSea" },
  orcid: { displayName: "ORCID" },
  html: { displayName: "HTML" },
  jquery: { displayName: "jQuery" },
  mui: { displayName: "MUI" },
  clickup: { displayName: "ClickUp" },
  hnm: { displayName: "H&M" },
  freefire: { displayName: "FreeFire", url: "https://ff.garena.com/en" },
  sekiro: {
    displayName: "Sekiro: Shadows Die Twice",
    url: "https://www.sekirothegame.com/home",
  },
  "iit-bombay": { displayName: "IIT Bombay", url: "https://www.iitb.ac.in" },
  "iit-madras": { displayName: "IIT Madras", url: "https://www.iitm.ac.in" },
  "iit-delhi": { displayName: "IIT Delhi", url: "https://home.iitd.ac.in" },
};


export default logoMeta;
