const logoAliases = {
  adonisjs: ["adonis"],
  alpinejs: ["alpine"],
  avajs: ["ava"],
  backbonejs: ["backbone"],
  blueprintjs: ["blueprint"],
  bluesky: ["bsky"],
  bulmaui: ["bulma"],
  bunjs: ["bun"],
  cassandradb: ["cassandra"],
  chakraui: ["chakra"],
  chatgpt: ["openai"],
  codeforces: ["cf"],
  cplusplus: ["cpp"],
  digitalocean: ["do"],
  discord: ["dc"],
  elementui: ["element"],
  emberjs: ["ember"],
  ethereum: ["eth"],
  expressjs: ["express"],
  facebook: ["fb"],
  faunadb: ["fauna"],
  flyio: ["fly"],
  framer: ["framer-motion"],
  gatsbyjs: ["gatsby"],
  golang: ["go"],
  gridsomejs: ["gridsome"],
  gruntjs: ["grunt"],
  instagram: ["insta"],
  javascript: ["js"],
  leetcode: ["lc"],
  louisvuitton: ["lv"],
  mariadb: ["maria"],
  marrionettejs: ["marionette"],
  microsoft: ["msft", "ms"],
  mochajs: ["mocha"],
  nestjs: ["nest"],
  nextjs: ["next"],
  nodejs: ["node"],
  nuxtjs: ["nuxt"],
  ola: ["olacabs"],
  pixijs: ["pixi"],
  prestodb: ["presto"],
  pugjs: ["pug"],
  radixui: ["radix"],
  reactjs: ["react"],
  ringcentral: ["rc"],
  rollupjs: ["rollup"],
  semanticui: ["semantic"],
  solidjs: ["solid"],
  typescript: ["ts"],
  unjs: ["un"],
  vuejs: ["vue"],
  woocommerce: ["woo"],
  youtube: ["yt"],
};

export default logoAliases;
